#!/usr/bin/env python
# this line is needed so the execution happens in python environment

"""
get and publish PID results for rudder 
"""
import rospy
from std_msgs.msg import Float32
from std_msgs.msg import Int64
from std_msgs.msg import Header
from boat_pid_control import rudderPID as rpid

goal_heading = 0

def store_goal(goal):
    global goal_heading
    goal_heading = goal

def publish_pid(current):
     h = Header()
     if not rospy.is_shutdown():
         rudder_pid = rpid.get_pid(current.data, goal_heading)
         rospy.loginfo('rudder pid: ' + str(rudder_pid))
         #update header time
         h.stamp = rospy.Time.now()
         publishPID.publish(rudder_pid)



def sail_react():
    rospy.Subscriber("/sensors/Compass", Int64, publish_pid)

    # save wind direction
    rospy.Subscriber("/planning/GoalHeading", Int64, store_goal)
    rospy.spin()

if __name__ == '__main__':
    try:
        rospy.init_node('pid_talker', anonymous=True)
        publishPID = rospy.Publisher('RudderPID', Float32, queue_size=10)
        sail_react()
    except rospy.ROSInterruptException: pass
