#!/usr/bin/env python
# this line is needed so the execution happens in python environment

"""
Script to find offset values for compass,
store them
"""

from os.path import expanduser
from boat_imu import magnetometer

SAMPLE_TIME = 1
home = expanduser("~")
f = open(home + '/boat_data_compass', 'w')

offset = magnetometer.get_offset(SAMPLE_TIME)
f.write(str(offset[0]) + '\n')
f.write(str(offset[1]) + '\n')
f.write(str(offset[2]) + '\n')
f.close()
print(offset)
