#!/usr/bin/env python
# this line is needed so the execution happens in python environment


import boat_imu.receive_imu as r_imu
import rospy
from std_msgs.msg import Int64
from std_msgs.msg import Header
from boat_imu.msg import IMU_msg

airPressure = r_imu.airPressure.copy()
accelerometer = r_imu.accelerometer.copy()
magnetometer = r_imu.magnetometer.copy()
gyroscope = r_imu.gyroscope.copy()

def imu_test_listener():
    rospy.init_node('listener', anonymous=True)
    print('test')
    rospy.loginfo('ros imu listener started')
    rospy.Subscriber("/sensors/AirPressure", Int64, r_imu.storeIntROS, airPressure)
    rospy.Subscriber(accelerometer['name'], IMU_msg, r_imu.store3dROS, accelerometer)
    rospy.Subscriber("/sensors/Magnetometer", IMU_msg, r_imu.store3dROS, magnetometer)
    rospy.Subscriber("/sensors/Gyroscope", IMU_msg, r_imu.store3dROS, gyroscope)
    rospy.spin()

if  __name__ == '__main__':
    imu_test_listener()
