#!/usr/bin/env python
# this line is needed so the execution happens in python environment


# script to publish 9DOF IMU data

import rospy
from std_msgs.msg import Int64
from std_msgs.msg import Header

def get_wind_dir():
    return 23

def talker():
    pubWindDir = rospy.Publisher('WindDirection', Int64, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    r = rospy.Rate(0.1) # in Hz
    h = Header()
    while not rospy.is_shutdown():
        # update header time
        h.stamp = rospy.Time.now()

        wind_dir = get_wind_dir()

        rospy.loginfo(wind_dir)
        pubWindDir.publish(wind_dir)

        r.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException: pass
