#!/usr/bin/env python
# this line is needed so the execution happens in python environment

"""
Script to calculate and publish
goal heading
"""
import rospy
from std_msgs.msg import Int64
from std_msgs.msg import Header
from sensor_msgs.msg import NavSatFix
#from boat_current_heading import goalHeading as goal
import time

#position=

def calc_heading()

   h = Header()
     while not rospy.is_shutdown():
        # update header time
        h.stamp = rospy.Time.now()
        
        #new_value = goal.get_heading(position, waypoint)
        rospy.loginfo(new_value)
        pubHeading.publish(new_value)


def heading_talker():
    try:
        rospy.Subscriber("fix", NavSatFix, calc_heading)
    except:
        rospy.Subscriber("simulated-fix", NavSatFix, calc_heading)
    # also update if a waypoint is published
    #rospy.Subscriber("waypoint", Int64, calc_heading)

if __name__ == '__main__':
    try:
        rospy.init_node('heading_talker', anonymous=True)
        publishHeading = rospy.Publisher('GoalHeading', Int64, queue_size=10)
        heading_talker()

    except rospy.ROSInterruptException: pass
