#!/usr/bin/env python
# this line is needed so the execution happens in python environment

"""
Script to calculate and publish
goal heading

"""
import rospy
from std_msgs.msg import Int64
from std_msgs.msg import Header
from boat_functions.msg import boat_3d
from sensor_msgs.msg import NavSatFix
from boat_curr_heading import goalHeading as goal
import time

current_waypoint = [0, 0]

def store_waypoint(wp):
    current_waypoint = [wp(0), wp(1)]

def publish_heading(position):
     h = Header()
     if not rospy.is_shutdown():
         heading = goal.calc_heading(position, current_waypoint)
         rospy.loginfo('goal heading' + str(heading))
         #update header time
         h.stamp = rospy.Time.now()
         # TODO: switch to heading message that includes header
         publishWaypoint.publish(heading)



def heading_react():
    print("check 2")
    rospy.Subscriber("fix", NavSatFix, publish_heading)
    rospy.Subscriber("simulatedFix", NavSatFix, publish_heading)

    #also update if a waypoint is published
    rospy.Subscriber("waypoint", boat_3d, store_waypoint)
    print("spinning")
    rospy.spin()

if __name__ == '__main__':
    try:
        rospy.init_node('heading_talker', anonymous=True)
        publishHeading = rospy.Publisher('GoalHeading', Int64, queue_size=10)
        print("check 1")
        heading_react()

    except rospy.ROSInterruptException: pass
