#!/usr/bin/env python
# this line is needed so the execution happens in python environment
import rospy
from boat_functions import test_printer as bf
from boat_oil_sensor import test as test
bf.test_printer()
test.test_oil_sensor_functions()
