#!/usr/bin/env python
# this line is needed so the execution happens in python environment
import rospy
from boat_functions import test_printer as bf
bf.test_printer()
"""
import boat_imu
from boat_imu import read_imu as ri
print("works")
ri.test_imu_functions()
"""
